services:
  - type: web
    name: psystudio-license-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    disk:
      name: psystudio-license-data
      mountPath: /app/data
      sizeGB: 1
